# -*- coding: utf-8 -*-
"""TinyDB Testing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k1kc-iDOfASib5lGwJx1YxZWxtbQbdu0
"""

!pip install tinydb

from tinydb import TinyDB       
db = TinyDB("todo_db.json")

new_item = {"name": "Book", "quantity": 5}
db.insert(new_item) 
new_item = {"name": "Book"}
db.insert(new_item)

print(db)
print(db.all())

items = [{"name": "Candles", "quantity": 10},{"name": "Balloons", "quantity": 50}]
db.insert_multiple(items)
# returns the index where the items are being inserted

from tinydb import Query
Todo = Query()

x = db.search(Todo.name == 'Book')
print(x)
y  = db.search(Todo.name == 'Copies') 
print(y)

x = db.get(Todo.name == 'Book')
print(x)
y = db.get(Todo.name == 'Copies') 
print(y)

print(db.get(Todo.name == 'Book'))
print(db.get(Todo.name == 'Copies'))

# Appending into the database
db.insert({"name": "Balloons", "quantity": 500}) 
print(db.count(Todo.name == 'Balloons'))

# finding the number of records in the database
print(len(db))

Database = db.all()
print(Database)

# Updating the data
db.update({'name': 'Books'}, Todo.name == 'Book')
print(db.all())

# Updating the quantity in all the records
db.update({'quantity': 10}) 
print(db.all())

# Deleting Data
print(db.remove(Todo.name == 'Cake'))                        
print(db.all())                
db.remove(Todo.name == 'Copies')
print(db.all())

# removes by index
db.remove(doc_ids=[2]) 
print(db.all())

# Deleting everything from the database
db.truncate()
print(db.all())